import type { ModelConfig } from './types.js';

const SYSTEM_B_ENDPOINTS = {
  endpoint: 'https://api.kie.ai/api/v1/jobs/createTask',
  pollEndpoint: 'https://api.kie.ai/api/v1/jobs/recordInfo',
} as const;

export const MODELS: ModelConfig[] = [
  // ── System A ────────────────────────────────────────────────
  {
    id: 'gpt4o-image',
    label: 'GPT-4o Image',
    apiSystem: 'a',
    endpoint: 'https://api.kie.ai/api/v1/gpt4o-image/generate',
    pollEndpoint: 'https://api.kie.ai/api/v1/gpt4o-image/record-info',
    aspectRatios: ['1:1', '3:2', '2:3'],
    maxImages: 4,
    supportsEnhance: true,
    supportsResolution: false,
  },
  {
    id: 'flux-kontext-pro',
    label: 'Flux Kontext Pro',
    apiSystem: 'a',
    endpoint: 'https://api.kie.ai/api/v1/flux/kontext/generate',
    pollEndpoint: 'https://api.kie.ai/api/v1/flux/kontext/recordInfo',
    aspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxImages: 1,
    supportsEnhance: true,
    supportsResolution: false,
  },
  {
    id: 'flux-kontext-max',
    label: 'Flux Kontext Max',
    apiSystem: 'a',
    endpoint: 'https://api.kie.ai/api/v1/flux/kontext/generate',
    pollEndpoint: 'https://api.kie.ai/api/v1/flux/kontext/recordInfo',
    aspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    maxImages: 1,
    supportsEnhance: true,
    supportsResolution: false,
  },
  {
    id: 'midjourney',
    label: 'Midjourney',
    apiSystem: 'a',
    endpoint: 'https://api.kie.ai/api/v1/midjourney/imagine',
    pollEndpoint: 'https://api.kie.ai/api/v1/midjourney/record-info',
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '2:3', '3:2'],
    maxImages: 4,
    supportsEnhance: false,
    supportsResolution: false,
  },
  // ── System B ────────────────────────────────────────────────
  {
    id: 'nano-banana-2',
    label: 'Nano Banana 2',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9', '4:1', '1:4', '8:1', '1:8', 'auto'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: true,
  },
  {
    id: 'nano-banana-pro',
    label: 'Nano Banana Pro',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9', 'auto'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: true,
  },
  {
    id: 'google/nano-banana',
    label: 'Nano Banana',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9', 'auto'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: false,
  },
  {
    id: 'gpt-image-2-text-to-image',
    label: 'GPT Image-2',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['auto', '1:1', '16:9', '9:16', '4:3', '3:4'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: true,
  },
  {
    id: 'ideogram/v3-text-to-image',
    label: 'Ideogram V3',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['square', 'square_hd', 'portrait_4_3', 'portrait_16_9', 'landscape_4_3', 'landscape_16_9'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: false,
  },
  {
    id: 'google/imagen4-fast',
    label: 'Imagen 4 Fast',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4'],
    maxImages: 4,
    supportsEnhance: false,
    supportsResolution: false,
  },
  {
    id: 'flux-2/pro-text-to-image',
    label: 'Flux 2 Pro',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: true,
  },
  {
    id: 'grok-imagine/text-to-image',
    label: 'Grok Imagine',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '2:3', '3:2'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: false,
  },
  {
    id: 'wan/2-7-image',
    label: 'Wan 2.7 Image',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '16:9', '9:16', '4:3', '3:4', '21:9', '8:1', '1:8'],
    maxImages: 4,
    supportsEnhance: false,
    supportsResolution: true,
  },
  {
    id: 'seedream/5-lite-text-to-image',
    label: 'Seedream 5 Lite',
    apiSystem: 'b',
    ...SYSTEM_B_ENDPOINTS,
    aspectRatios: ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'],
    maxImages: 1,
    supportsEnhance: false,
    supportsResolution: true,
  },
];

export function getModel(id: string): ModelConfig {
  const model = MODELS.find(m => m.id === id);
  if (!model) throw new Error(`Unknown model: ${id}`);
  return model;
}
